spring:
    datasource:
        url: jdbc:mysql://localhost:3306/car_service
        username: root
        password: Pass@123
    jpa:
        hibernate:
            ddl-auto: update
server:
    port: 9099

